### ISSUE TITLE
Exception in Golestan main page

### ISSUE THREAD

**Issue by gsoosk** [alitoufighi/golestan-grade-checker#5]
It seems there are some changes in Golestan main page and script got an exception in finding a frame. 
```
Traceback (most recent call last):
  File "main.py", line 261, in <module>
    ggc.run()
  File "main.py", line 86, in run
    self._go_to_etelaate_jame_daneshjoo_page()
  File "main.py", line 160, in _go_to_etelaate_jame_daneshjoo_page
    self._switch_to_main_frame(2)
  File "main.py", line 139, in _switch_to_main_frame
    frame = self.driver.find_element_by_xpath('/html/frameset/frameset/frame[2]')
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/frameset/frameset/frame[2]
```

**Comment by alitoufighi** [comment]
It works like a charm for me.
There may be some chance that the desired page or frame hasn't been loaded during timeout time (that 20 seconds sleep time); so it can't find that frame and causes problems.
Do you have any recommendations to wait until the whole page is loaded?

**Comment by gsoosk** [comment]
I think it can be handled by searching for that frame and wait if it wasn't loaded.

**Comment by alitoufighi** [comment]
I think I tried this some times ago but I didn't find any method to do this in Selenium. Maybe we have to spend more time to solve it by ourselves in this way.
What about putting any independent blocks of code (in a single frame) in a while true loop and let it sleep for a while when an exception occurs and then try again? :-?

**Comment by gsoosk** [comment]
It's a good idea. Actually, I think it's a better solution and have less load on the system.
